import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import rateLimit from 'express-rate-limit';
import auth from './routes/auth.js';
import services from './routes/services.js';
import user from './routes/user.js';
import orders from './routes/orders.js';
import payments from './routes/payments.js';
import admin from './routes/admin.js';
import settings from './routes/settings.js';
const app = express();
const configuredFrontendOrigin = process.env.FRONTEND_URL || 'http://localhost:5173';
const allowedFrontendOrigins = new Set([configuredFrontendOrigin, 'http://localhost:5173', 'http://localhost:5174', 'http://localhost:5175']);
app.use(helmet()); app.use(cors({ origin: (origin, callback) => { if (!origin || allowedFrontendOrigins.has(origin)) return callback(null, true); return callback(new Error('Origin not allowed')); }, credentials: true })); app.use(express.json({ limit: '1mb' })); app.use(cookieParser());
app.use('/api/auth', rateLimit({ windowMs: 15 * 60 * 1000, limit: 100 }), auth);
app.use('/api/services', services); app.use('/api/user', user); app.use('/api/orders', orders); app.use('/api/payments', payments); app.use('/api/admin', admin); app.use('/api/settings', settings);
app.get('/api/health', (_req, res) => res.json({ success: true, data: { status: 'ok', demoMode: process.env.DEMO_MODE === 'true' } }));
app.use((err: any, _req: express.Request, res: express.Response, _next: express.NextFunction) => { console.error(err); const isValidationError = err?.name === 'ZodError'; const validationMessage = isValidationError && Array.isArray(err.issues) ? err.issues.map((issue: any) => `${issue.path?.join('.') || 'request'}: ${issue.message}`).join('; ') : ''; res.status(isValidationError ? 400 : 500).json({ success: false, message: validationMessage || (isValidationError ? 'Invalid request data' : 'Something went wrong') }); });
const port = Number(process.env.PORT || 4000); app.listen(port, () => console.log(`SocialBoost API listening on ${port}`));
